name: Deploy core infrastructure

on:
  push:
    branches:
      - 'main'
    paths:
      - 'modules/networking/**'
      - 'core_infrastructure/**'
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: ./core_infrastructure

jobs:

  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform workspace select or create dev
        run: terraform workspace select -or-create dev
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform plan
        run: terraform plan -var="rg_name=maja-rg-dev"
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform apply
        run: terraform apply -var="rg_name=maja-rg-dev"
        working-directory: ${{ env.WORKING_DIR }}

  staging:
    needs: dev
    runs-on: ubuntu-latest
    steps:
      - name: Chekcout
        uses: actions/checkout@v3

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform workspace select or create staging
        run: terraform workspace select -or-create staging
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform plan
        run: terraform plan -var="rg_name=maja-rg-staging"
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform apply
        run: terraform apply -var="rg_name=maja-rg-staging"
        working-directory: ${{ env.WORKING_DIR }}

  prod:
    needs: staging
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform workspace select or create prod
        run: terraform workspace select -or-create prod
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform plan
        run: terraform plan -var="rg_name=maja-rg-prod"
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform apply
        run: terraform apply -var="rg_name=maja-rg-prod"
        working-directory: ${{ env.WORKING_DIR }}
