name: Validate core infrastructure

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'modules/networking/**'
      - 'core_infrastructure/**'
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: ./core_infrastructure
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform fmt
        run: terraform fmt
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform validate
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}

      - name: Tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ env.WORKING_DIR }}
          github_token: ${{ env.GITHUB_TOKEN }}
